FROM python:3.11-slim

WORKDIR /engine

COPY engine/requirements.txt /engine/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy entire engine folder safely
COPY engine/ /engine/

COPY docker/entrypoint-engine.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENV AUTH_LOG_PATH=/data/auth.log
ENV ALERTS_PATH=/output/sample_output.json
ENV REPORT_MD=/output/report.md
ENV REPORT_JSON=/output/report.json
ENV RUN_INTERVAL_SECONDS=10

CMD ["/entrypoint.sh"]